spring:
  application:
    name: inventory_service

  # Timezone configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://ep-shy-hall-adchttnv-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_CAmuOv5L4gSG
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  rabbitmq:
    host: localhost
    port: 5672

